name: Keep Strapi Awake

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Strapi
        run: curl -s -o /dev/null -w "%{http_code}\n" https://hunterproperty.onrender.com
